# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=600)),
                ('post_subtitle', models.CharField(max_length=1000)),
                ('post_pub_date', models.DateTimeField(verbose_name='date published')),
                ('post_author', models.CharField(max_length=100)),
                ('post_text', models.TextField()),
            ],
        ),
    ]
